README.rst

There's nothing in here needs PRing - I just noticed a few really small typos - thought you might want to know about them.

Fix really minor typos

---

schwifty/iban-registry.json
tests/test_iban.py

Hi, I made some updates to the existing IBAN JSON. We wanted to bring this more inline with the latest ISO 13616 IBAN Registry: https://www.swift.com/file/43411/download?token=kPb-YbhV 
Please review. Tests pass successfully.

SI IBAN spec and other IBAN spec updates

---

schwifty/common.py
tests/test_bic.py
tests/test_iban.py

This allows including objects into sets and stuff:
```python
set([IBAN('DE42430609677000534100'), IBAN('DE04750909000007408418'), IBAN('DE42430609677000534100')])
```

Add `__hash__()` method to `Base`

---

schwifty/bank_registry/manual_es.json

I still owe the new custom exceptions implementation mentioned in #19 
Thanks!

A new Spanish bank

---

.github/workflows/lint.yml
docs/source/index.rst

- added doc8 lint to github workflows
- fixed line lenght issues reported by doc8

Doc8 - added documentation (rst) lint to github workflows

---

schwifty/bank_registry/generated_at.json
schwifty/bank_registry/generated_cz.json
schwifty/bank_registry/generated_fi.json
schwifty/bank_registry/generated_hr.json
schwifty/bank_registry/generated_lv.json
schwifty/bank_registry/generated_pl.json
schwifty/bank_registry/generated_si.json
scripts/get_bank_registry_at.py
scripts/get_bank_registry_cz.py
scripts/get_bank_registry_fi.py
scripts/get_bank_registry_hr.py
scripts/get_bank_registry_lv.py
scripts/get_bank_registry_pl.py
scripts/get_bank_registry_si.py

Hi,
Following the original script for BE, I did some research on others and I found a couple of others for:
Austria
Croatia
Finland
Latvia
Poland
Slovenia
Looking forward to feedback.

Feature/generate bic for AT, HR, CZ, FI, LV, PL & SI

---

schwifty/bank_registry/generated_nl.json
scripts/get_bank_registry_nl.py

As promised in in https://github.com/mdomke/schwifty/issues/34

Added scraper script for NL-bic list

---

schwifty/bank_registry/generated_sk.json
scripts/get_bank_registry_sk.py

Hi, we are using your module at our company and it is very helpful. However we need to process Slovak IBANs, including getting details about the bank from the IBAN. Therefore we prepared a bank registry file with Slovak banks. The file was generated from the official Slovak national bank registry: https://www.nbs.sk/en/payment-systems/directories/directory-sk
Thank you for your work.

Added SK banks

---

schwifty/bank_registry/manual_at.json
schwifty/bank_registry/manual_ch.json
schwifty/bank_registry/manual_dk.json
schwifty/bank_registry/manual_es.json
schwifty/bank_registry/manual_gb.json
schwifty/bank_registry/manual_ie.json
schwifty/bank_registry/manual_il.json
schwifty/bank_registry/manual_it.json
schwifty/bank_registry/manual_tr.json

here are some bank registry which are collected during data developing，hope it helpful

add some bank registry

---

schwifty/bank_registry/manual_is.json

I added the Icelandic banks to a manual_is.json file. Thanks for this package.

Added manual_is.json

---

schwifty/bank_registry/manual_es.json

Added N26 neobank in Spain Code

n26 neobank spain code

---

schwifty/iban_registry/generated.json

Hello sir, thank you for good work. 
I correct Czech IBAN to use branch_code attribute. 
Thank you for allow request. 
Milda Dvorak

add branch_code at Czech IBAN

---

scripts/get_bank_registry_nl.py

The source Excel file has a blank line (78) in it which ends up in the [generated_nl.json](https://github.com/mdomke/schwifty/blob/master/schwifty/bank_registry/generated_nl.json#L587-L592) file. While I would love to fix the source we'll have to settle for filtering it out in the script.

#73 Skip empty lines in Dutch bank excel file.

---

schwifty/checksum/__init__.py
schwifty/checksum/france.py
schwifty/iban.py
schwifty/iban_registry/generated.json

commit associated with issue #65 
Once again, code is kinda sloppy (but it's working), I'd rather use it as a base for checksum/france.py

Creating French BBAN (RIB) checksum algorithm

---

schwifty/iban_registry/overwrite.json

Source
https://www.cbj.gov.jo/EchoBusV3.0/SystemAssets/PDFs/EN/03-Instructions%20for%20implementing%20International%20Bank%20Account%20Number_Edited.pdf

Fixed bank_code position for Jordan.

---

schwifty/iban.py
tests/test_iban.py

Allow getting bank names from IBAN

---

.gitignore
schwifty/bank_registry/manual_sa.json

I have added JSON for SWIFT and BIC Codes of Saudi Arabia from https://www.theswiftcodes.com/saudi-arabia/ . I have followed the format mentioned in README.md for the bank registry and ran pre-commit/black on JSON as well.

added Saudi Arabia bic/swift codes to bank_registry

---

schwifty/bank_registry/generated_hu.json
scripts/get_bank_registry_hu.py
scripts/requirements.txt
scripts/update-all.sh

Hi @mdomke,
thanks for merging and releasing my PR with Bulgarian BIC codes, we've tested it in production and it works as expected.
I've created this PR with Hungarian BIC codes. Now even with generate script. 
Data is fetched from National Bank of Hungary from some XLSX file I think may be updated and should work after some time.
I'll create one more PR with Romanian BIC codes with similar functionality.
It would be great if you've reviewed the PR and released it together, if you don't mind.
Thank you for actively maintaining this package, it means a lot for us 💯

Added Hungarian BIC codes with generator

---

schwifty/bank_registry/generated_ro.json
scripts/get_bank_registry_ro.py
scripts/update-all.sh

Hi @mdomke,
There is the second PR with Romanian BIC codes with generator script.
It would be great if you've reviewed the PR and released it together, if you don't mind.
Thank you for actively maintaining this package, it means a lot for us 💯

Added Romanian BIC codes with generator

---

schwifty/checksum/__init__.py
schwifty/iban_registry/overwrite.json
schwifty/registry.py
tests/test_iban.py

Example IBAN for test was taken from: https://www.iban.com/structure
The structure taken from: https://en.wikipedia.org/wiki/International_Bank_Account_Number

Senegal iban validation

---

scripts/get_bank_registry_at.py
scripts/get_bank_registry_be.py
scripts/get_bank_registry_cz.py
scripts/get_bank_registry_de.py
scripts/get_bank_registry_fi.py
scripts/get_bank_registry_hr.py
scripts/get_bank_registry_hu.py
scripts/get_bank_registry_lv.py
scripts/get_bank_registry_nl.py
scripts/get_bank_registry_pl.py
scripts/get_bank_registry_se.py
scripts/get_bank_registry_si.py
scripts/get_bank_registry_sk.py
scripts/requirements.txt

As i got an error on processing belgium data, i started to switch the scripts to pandas for simpler handling. 
Let me know if this could be a way to go, i will convert the other scripts, too.

Switching to pandas

---

schwifty/bank_registry/generated_se.json
scripts/Dockerfile_se
scripts/get_bank_registry_se.py

The latest list of Banks in Sweden is available only in PDF.
This PR uses the list from 2022-06-23 to update the registry, and also updates the script to parse the data from the PDF.

Update swedish bank registry

---

schwifty/bank_registry/generated_nl.json

@mdomke hello again! please check whenever you have some free time 🙏🏽

feat(bic): added NL bank

---

schwifty/bank_registry/manual_it.json

@mdomke added some new IT banks

fix(bic): added new IT banks

---

schwifty/bank_registry/manual_pt.json

fix(bic): added new PT banks

---

schwifty/bank_registry/manual_cy.json
schwifty/bank_registry/manual_gr.json
schwifty/bank_registry/manual_it.json

@mdomke please have a look whenever you get the chance

Updated BIC codes for GR, CY & added new ones for IT

---

.github/workflows/lint-and-test.yml
setup.cfg
tox.ini

This PR adds Python 3.11 in test matrix in CI run.

chore(ci): add Python 3.11 in test matrix

---

schwifty/bank_registry/generated_nl.json
schwifty/bank_registry/manual_cy.json
schwifty/bank_registry/manual_it.json
schwifty/bank_registry/manual_pt.json

@mdomke updates some countries' json files, feel free to take a look! 😁

Added new banks for IT, fixed bic codes for CY, PT

---

schwifty/checksum/__init__.py
schwifty/checksum/netherlands.py
tests/test_checksum.py

Add checksum validation for Netherlands

---

schwifty/bank_registry/manual_fr.json

Add MEMO BANK and REVOLUT

---

schwifty/bank_registry/manual_fr.json

Add Lydia Solution FR bank

---

schwifty/bank_registry/manual_fr.json

Add ARKEA BP Brest — Federal Finance

---

schwifty/bank_registry/manual_ie.json

Add SumUp Limited bank_code

---

schwifty/bank_registry/manual_mc.json
tests/test_bic.py

Start Monaco IBAN registry.

---

schwifty/bank_registry/manual_fr.json

Add anytime neobank

---

schwifty/bank_registry/manual_tr.json

Türkiye banks registry updated from [The Banks Association of Türkiye](https://www.tbb.org.tr/modules/banka-bilgileri/banka_Listesi.asp?tarih=5/1/2024)

Update TR banks

---

schwifty/bank_registry/generated_es.json

Added BIC / SWIFT code of BAnk Revolut Spain

added Bank Revolut Spain

---

schwifty/checksum/norway.py
tests/test_checksum.py

Fixes https://github.com/mdomke/schwifty/issues/190

Fix Norway checksum validation

---

schwifty/iban_registry/generated.json

Running `scripts/get_iban_registry.py` gave me this result.

Update IBAN registry spec

---

schwifty/bank_registry/generated_at.json
schwifty/bank_registry/generated_de.json
schwifty/bank_registry/generated_hu.json
schwifty/bank_registry/generated_it.json
schwifty/bank_registry/generated_nl.json
schwifty/bank_registry/generated_no.json
schwifty/bank_registry/generated_pl.json
schwifty/bank_registry/generated_si.json
scripts/get_bank_registry_de.py

Some errors occured in some scripts...

Update generated according to script spec

---

schwifty/bank_registry/manual_fr.json
tests/test_bic.py

Hello,
Some perfectly valid IBANs don't pass schwifty validations. I extracted theirs bics and bank codes to add to the list, so everyone can make a good use of it.
Thank you for the nicest package! 👍

Add French Polynesian banks to the registry

---

schwifty/bank_registry/generated_be.json

There have been some mergers. Bank registry is no longer in sync with the data from the NBB
- AXA Bank is integrated into Crelan
- bpost bank is integrated into BNP Paribas Fortis

Update BE bank registry

---

CHANGELOG.rst
schwifty/common.py
tests/test_bic.py
tests/test_iban.py

Allow objects to be deepcopied

---

schwifty/bank_registry/manual_fr.json

Fixes #225
Through an holding: https://lu.lei.report/LEI/VH4XNLMLBEU4NGDFRN07

Fix SOCIETE GENERALE name

---

schwifty/bank_registry/manual_fr.json

Add new French Banks

---

schwifty/bank_registry/manual_fr.json

Add a few french banks — Reviewed

---

schwifty/bank_registry/manual_gb.json

Add NOVEBA LIMITED GB bank
