- schwifty/bic.py
- tests/test_bic.py
This pull requests enables getting a bank's name and short_name as bank_name and bank_short_name properties of a BIC object. This data is already present in bank-registry.json .
This also adds the two new fields to the appropriate tests. Testing is refactored to avoid checking the same thing multiple times. The order of the BIC properties in the code is changed to follow the structure of a BIC. Additionally, a docstring typo is fixed.
> Add properties for long and short bank name to BIC

- schwifty/bank_registry/manual_es.json
- schwifty/bank_registry/manual_gb.json
This is what I have for now. Added, among others, BBVA, Banco Santander, CaixaBank, Banco Sabadell, and ING.
I'll continue adding more banks as a get more bank accounts to extract the needed info. I'll also work on the new Exceptions as discussed in #19.
I would need this merged and released to use the new banks data in my project. Unless there is an easy way to use a tarball version from my own repo. I used to do so via `dependency_links` but it looks like pbr doesn't play well with that snapshot-like option. What I have done is to tag my update as 2020.01.1 in my repo and setup my `dependency_links` to point to my repo's tarball (`https://github.com/osroca/schwifty/tarball/2020.01.1#egg=schwifty-2020.01.1`). This caused the following error when installing my project:
```
File …
```
> Adding some Spanish banks and Halifax from UK

- schwifty/bank_registry/generated_fi.json
- schwifty/bank_registry/manual_ch.json
- schwifty/bank_registry/manual_fr.json
- schwifty/bank_registry/manual_gb.json
- scripts/get_bank_registry_fi.py
Hello ! Here is some data we can use in this lib. Thanks for having created it (& maintained)
The data is generated from a (private) list of IBANs / BICs. The bank name is extracted from LEI dataset (details below). Then the bank code is extracted using `schwifty`.
For most of the data, it should be fine (I checked the more common).
Maybe you know already what is it, but since I found no mention of it, I'm writing a quick summary just in case.
Basically, all financials actors have a unique identifier called *LEI* (Legal Entity Identifier), and for this LEI, some metadata are attached (notably, bank name). Finally there is a mapping between BICs and LEIs, so you can retrieve bank name from BIC.
*References*
- [glei website](https://www.gleif.org/en/about-lei/introducing-the-legal-entity-ide …
> Add FR, CH & GB banks (+quick fix over FI bics)

- schwifty/iban.py
- tests/test_iban.py
Check digits might still be invalid even if the condition
numeric(IBAN) % mod 97 == 1
applies. So the above is a necessary but not a sufficient condition.
closes #42
> Compare check digits if quick check passes

- schwifty/checksum/__init__.py
- schwifty/checksum/belgium.py
- schwifty/iban.py
- tests/test_checksum.py
- tests/test_iban.py
Implements the BBAN checksum check for Belgium.
Following the discussion in #49, I went ahead to implement the BBAN check for Belgian banks.
The check for Belgium itself should be quite simple, see e.g. http://www.credit-card.be/BankAccount/ValidationRules.htm#BE_Validation
The BBAN is represented  by XXX-YYYYYYY-ZZ where:
- XXX: the bank code code
- YYYYYYY: the account number
- ZZ: the checksum == XXXYYYYYYY % 97
I also did update the method to add checksums to generated IBANs.
> Implements BE BBAN checksum check

- docs/source/examples.rst
- schwifty/bank_registry/generated_se.json
- scripts/get_bank_registry_se.py
Script for Swedish bank registry taken from the SwedishBankers association
https://www.swedishbankers.se/fraagor-vi-arbetar-med/betalningar/ny-nordisk-betalningsinfrastruktur/iban-och-svenskt-nationellt-kontonummer/
> Script for Swedish bank registry

- schwifty/bic.py
I just found that I did not add Sweden to this list in `class BIC`
> Add Sweden as available for BIC class usage

- schwifty/registry.py
This fixes an issue that occurs on platforms that don't use UTF-8 as default encoding
> Specify encoding when reading registry files

- schwifty/iban.py
According to the Register of European Account Numbers (ECBS TR 201V3.9) (page 79), the Italian IBAN covers San Marino and so it also has a similar check digit.
> Add check sum for San Marino

- schwifty/bank_registry/manual_ie.json
Hi there,
i came noticed that the bank of ireland was missing in the registry. So I took the liberty to add them.
The only question I got is if you like to maintain primary BICs with or without the `XXX` suffix, as there was already a mixture in the file for ireland
> feat: add bank of ireland to registry

- setup.cfg
`home_page` is an (undocumented?) alias for `url`, so use `url` instead (source: https://github.com/pypa/setuptools/blob/2582a8bc1a93d9876cf62d4f83ccb60a5110798c/setuptools/config/setupcfg.py#L469)
add `project_urls` which PyPI will render with nice icons on the side bar (example: https://pypi.org/project/django-htmx/)
> Update package URL's

- tox.ini
'hacking' only exists to set up flake8, but that is in the `lint` testenv instead.
> Remove 'hacking' from tox envs

- schwifty/bank_registry/manual_ie.json
Hello @mdomke!
At [Plum](https://github.com/withplum) we've been using your library for some time and we love your work. Having said that, I'd like to add support for some additional IE banks that we need schwifty to have available.
I have manually added all these institutions and cross checked with [Wise](https://wise.com/us/swift-codes/countries/ireland) for each bank's `bic`, `bank_code` and names (`name` and `short_name`)
Let me know what you think! Thanks!
> feat(app): added more IE banks

- schwifty/bank_registry/generated_hu.json
- scripts/get_bank_registry_hu.py
Hello @mdomke,
I'm sorry, but I made a mistake in my previous PR with Hungarian bank codes #96, this PR corrects it. 
I've checked the Hungarian IBAN format https://bank.codes/iban/structure/hungary/, where bank codes are in `3n` format, which I've corrected in the generator script and generated valid bank_codes.
> Fixed Hungary bank codes to be numeric

- schwifty/bank_registry/manual_gr.json
Hello @mdomke!
As you already probably know, at [Plum](https://github.com/withplum) we've been using your library for some time. Since we need more banks, I'm adding support for GR banks to have them available through schwifty.
I have manually added these institutions and cross checked with [Wise](https://wise.com/us/swift-codes/countries/greece) and [Bank of Greece](https://www.bankofgreece.gr/) for each bank's bic, bank_code and names (name and short_name).
Let me know if you need anything!
> feat(app): added GR banks

- schwifty/bank_registry/manual_gr.json
Fix Viva payment bank code information in the manually curated gr file.
> fix: Correct bank code for Viva Payment

- schwifty/bank_registry/manual_cy.json
Fix bank codes for the following banks:
- ASTROBANK PUBLIC COMPANY LIMITED
- BANK OF CYPRUS PUBLIC COMPANY LIMITED
- HELLENIC BANK PUBLIC COMPANY LTD
> fix: Correct bank codes for Cypriot banks

- schwifty/bank_registry/generated_no.json
- scripts/get_bank_registry_no.py
- scripts/update-all.sh
This PR adds a script to generate a bank registry for Norwegian banks. It uses the official source, available at https://www.bits.no/document/iban/
Relevant links: https://bits.no/en/iban
> Add norwegian bank registry

- .github/workflows/lint-and-test.yml
- setup.cfg
- tox.ini
This PR adds Python 3.12 in test matrix.
Note: I had to allow pre releases since Python 3.12 is still in beta and will land soon in release candidate.
> chore(python): add Python 3.12 in test matrix

- schwifty/bank_registry/manual_fr.json
Since October 2nd, Boursorama is now called Boursobank
source : https://www.boursobank.com/aide-en-ligne/mon-espace-client/boursorama-banque-devient-boursobank/question/comment-va-se-derouler-le-passage-de-boursorama-banque-vers-boursobank-91152739
> Boursorama is now called Boursobank

- schwifty/bic.py
- tests/test_bic.py
A new standard [ISO 9362:2022(E)](https://www.iso.org/standard/84108.html) allows digits as a bank code in BIC.
I came across this when I was making quarter updates in SEPA documents in the Bank of Lithuania.
> Allow digits as a bank code in BIC according to ISO 9362:2022(E)

- schwifty/bank_registry/manual_fr.json
I tried to use the registry to findout the BIC from the couple `("FR", "17448")` but couldn't find it in the registry.
> Add OKALI to the list of French banks.

- schwifty/bank_registry/manual_fr.json
I tried to use the registry to find out the BIC from the couple ("FR", "17418") but couldn't find it in the registry.
> Add missing SHINE bank

- schwifty/bank_registry/generated_cz.json
- scripts/get_bank_registry_cz.py
- tests/test_registry.py
Czech registry seems to be stored in `latin-1` encoding but [read](https://github.com/mdomke/schwifty/pull/75/files) in `utf-8` which leads to wrong bank names.
> Fix CZ encoding

- schwifty/bank_registry/manual_es.json
Bnext is a spanish neobank that offers bank accounts: https://bnext.es/cuenta
It is registerd in banco de españa (https://www.bde.es/webbe/en/estadisticas/otras-clasificaciones/clasificacion-entidades/listas-instituciones-financieras/listas-instituciones-financieras-monetarias-pais/lista-mfi-es.html)
> Add bnext to manual ES registry

- .github/workflows/lint-and-test.yml
- schwifty/registry.py
Also tweak CI/CD so that the tests run on each Python version (formally hatch ignored the configured Python version in favour of a global 3.12 environment, hiding this issue).
Fixes #220
> Fix Python 3.8 compatibility

- schwifty/bank_registry/manual_es.json
Modular is a bank which is already in other countries' registry, but the spanish branch was missing
It is registered in banco de españa (https://www.bde.es/webbe/en/estadisticas/otras-clasificaciones/clasificacion-entidades/listas-instituciones-financieras/listas-instituciones-financieras-monetarias-pais/lista-mfi-es.html)
> Add modulr to ES registry

- .github/workflows/lint-and-test.yml
- CHANGELOG.rst
- pyproject.toml
- schwifty/bban.py
- schwifty/registry.py
Python 3.8 is officially not supported anymore since October 2024. Removing support for this version, allows us to use more modern syntax features and keep the code up to speed with the development of the language.
> Remove support for deprecated Python version 3.8

- pyproject.toml
Should be picked up by PyPI and others.
Currently, schwifty appears in PyPI search results with a description of "None".
> Add short project description

- pyproject.toml
- schwifty/iban_registry/overwrite.json
- tests/test_iban.py
- uv.lock
Polish IBANs have only one 8-digit bank code (often referred
in official documents as "bank branch number" or "branch
identifier") – it should not be split into three segments,
as was done in version 2024.01.1.
The changes in v2024.01.1 were based on a Wiki article that
was clearly incorrect. The official SWIFT document referenced
in the article (https://www.swift.com/resource/iban-registry-pdf)
always provided this information. The same information can be
found on the official website of the National Bank of Poland:
https://nbp.pl/pl/statystyka-i-raportowanie-finansowe/rynki-finansowe/iban-bic/
The Wiki article was recently updated when we came across it.
Although it's called a "branch identifier" or "bank branch number",
I believe in schwifty's terminology it's simply "bank_code." …
> Fix Polish IBAN specification
